apiVersion: v1
kind: Pod
metadata:
  name: obs-gpu-pod
spec:

  containers:
    - name: obesity-processor
      image: docker.io/cimartinezvillar/obesity-sentinel:cuda
      imagePullPolicy: IfNotPresent
      workingDir: /
      
      env:
        - name: DATA_DIR
          value: /data

        # NRP
        - name: RCLONE_CONFIG_NRP_TYPE
          value: s3
        - name: RCLONE_CONFIG_NRP_PROVIDER
          value: Other
        - name: RCLONE_CONFIG_NRP_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: access
              name: rconfig
        - name: RCLONE_CONFIG_NRP_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: secret
              name: rconfig
        - name: RCLONE_CONFIG_NRP_ENDPOINT
          value: https://s3-central.nrp-nautilus.io

      resources:
        limits:
          memory: 32Gi
          cpu: 16
          nvidia.com/gpu: 1
        requests:
          memory: 32Gi
          cpu: 16
          nvidia.com/gpu: 1

      volumeMounts:
        - mountPath: /obesity-images
          name: obesity-vol-mount
          readOnly: false

        - mountPath: /dev/shm
          name: dshm

      command: ["sleep", "infinity"]

  volumes:
    - name: obesity-vol-mount
      persistentVolumeClaim:
        claimName: obesity-pvc-clean

    - name: dshm
      emptyDir:
        medium: Memory

  nodeSelector:
    nautilus.io/disktype: nvme

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: nvidia.com/gpu.product
              operator: In
              values:
                - NVIDIA-GeForce-RTX-2080-Ti