apiVersion: v1
kind: Pod
metadata:
  name: obesity-pod
spec:
  containers:

    #container name/image
    - name: obesity-downloader-0
      image: docker.io/cimartinezvillar/obesity-downloader
      workingDir: /
      env:
        #WORKDIR
        - name: DATA_DIR
          value: /data

        # ESA
        - name: RCLONE_CONFIG_ESA_TYPE
          value: s3
        - name: RCLONE_CONFIG_ESA_PROVIDER
          value: Other
        - name: RCLONE_CONFIG_ESA_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: esa_access
              name: rconfig
        - name: RCLONE_CONFIG_ESA_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: esa_secret
              name: rconfig
        - name: RCLONE_CONFIG_ESA_ENDPOINT
          value: s3.dataspace.copernicus.eu

        # NRP
        - name: RCLONE_CONFIG_NRP_TYPE
          value: s3
        - name: RCLONE_CONFIG_NRP_PROVIDER
          value: Other
        - name: RCLONE_CONFIG_NRP_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: access
              name: rconfig
        - name: RCLONE_CONFIG_NRP_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: secret
              name: rconfig
        - name: RCLONE_CONFIG_NRP_ENDPOINT
          value: https://s3-central.nrp-nautilus.io


      #container limit/request
      resources:
        limits:
          memory: 8Gi
          cpu: 4
        requests:
          memory: 8Gi
          cpu: 4

      #container vol mounts
      volumeMounts:
        - mountPath: /obesity-images
          name: obesity-vol-mount
          readOnly: false

      #execute after init
      command: ["sh", "-c", "sleep infinity"]

  volumes:
    - name: obesity-vol-mount
      persistentVolumeClaim:
        claimName: obesity-pvc-clean